"""Default print formats for all Reactome DatabaseObjects."""

__copyright__ = "Copyright (C) 2018-2019, DV Klopfenstein. All rights reserved."
__author__ = "DV Klopfenstein"

SCH2FMT = {
   'abbreviation': '{abbreviation:8}',
   'accession': '{accession:8}',
   'accessUrl': '{accessUrl:8}',
   'address': '{address:8}',
   'alteredAminoAcidFragment': '{alteredAminoAcidFragment:8}',
   'chapterTitle': '{chapterTitle:8}',
   'coordinate': '{coordinate:8}',
   'databaseName': '{databaseName:8}',
   'dateTime': '{dateTime:8}',
   'dbId': '{dbId:7}',
   'definition': '{definition:8}',
   'diagramHeight': '{diagramHeight:8}',
   'diagramWidth': '{diagramWidth:8}',
   'displayName': '{displayName}',
   'doi': '{doi:8}',
   'ecNumber': '{ecNumber:8}',
   'endCoordinate': '{endCoordinate:8}',
   'endPositionInReferenceSequence': '{endPositionInReferenceSequence:8}',
   'firstname': '{firstname:8}',
   'hasDiagram': '{hasDiagram:8}',
   'identifier': '{identifier:8}',
   'initial': '{initial:8}',
   'ISBN': '{ISBN:8}',
   'isChimeric': '{isChimeric:8}',
   'isInDisease': '{isInDisease:8}',
   'isInferred': '{isInferred:8}',
   'isOrdered': '{isOrdered:8}',
   'journal': '{journal:8}',
   'maxUnitCount': '{maxUnitCount:8}',
   'minUnitCount': '{minUnitCount:8}',
   'name': '{name:8}',
   'note': '{note:8}',
   'oldStId': '{oldStId:8}',
   'orcidId': '{orcidId:8}',
   'pages': '{pages:8}',
   'project': '{project:8}',
   'pubMedIdentifier': '{pubMedIdentifier:8}',
   'referenceType': '{referenceType:8}',
   'releaseDate': '{releaseDate:8}',
   'releaseStatus': '{releaseStatus:8}',
   'schemaClass': '{schemaClass:8}',
   'score': '{score:8}',
   'secondCoordinate': '{secondCoordinate:8}',
   'speciesName': '{speciesName:8}',
   'startCoordinate': '{startCoordinate:8}',
   'startPositionInReferenceSequence': '{startPositionInReferenceSequence:8}',
   'stIdVersion': '{stIdVersion:8}',
   'stId': '{stId:13}',
   'surname': '{surname:8}',
   'synonym': '{synonym:8}',
   'systematicName': '{systematicName:8}',
   'taxId': '{taxId:8}',
   'text': '{text:8}',
   'title': '{title:8}',
   'uniformResourceLocator': '{uniformResourceLocator:8}',
   'url': '{url:8}',
   'volume': '{volume:8}',
   'year': '{year:8}',
}


# Copyright (C) 2018-2019, DV Klopfenstein. All rights reserved.
